baseURL = 'https://esotericbullshit.net'
languageCode = 'en-us'
title = 'esoteric bullshit'
theme = "psychicwound"

enableInlineShortcodes = 'true'
summaryLength = '25'
paginate = 3

[menu]
    [[menu.nav]]
    identifier = "home"
    name = "Home"
    pre = "./svg/home.svg"
    url = "/"
    weight = 1

    [[menu.nav]]
    identifier = "rss"
    name = "RSS"
    pre = "./svg/rss.svg"
    url = "/index.xml"
    weight = 2