baseURL = 'https://esotericbullshit.net'
languageCode = 'en-us'
title = 'esoteric bullshit'
theme = "psychicwound"

enableInlineShortcodes = 'true'
summaryLength = '25'
paginate = 10

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = ['templates/*']

[menu]
    [[menu.nav]]
    identifier = "home"
    name = "Home"
    pre = "/svg/home.svg"
    url = "/"
    weight = 1

    [[menu.nav]]
    identifier = "uses"
    name = "Uses"
    pre = "/svg/device-desktop.svg"
    url = "/uses"
    weight = 2

    [[menu.nav]]
    identifier = "rss"
    name = "RSS"
    pre = "/svg/rss.svg"
    url = "/index.xml"
    weight = 3    

[permalinks]
  [permalinks.page]
    week-notes = '/week-notes/:slug/'
  [permalinks.section]
    week-notes = '/week-notes/'

[params]
  description = 'arcane shit that I am incomprehensibly fixated on'
  images = 'ogi.png'
  title = 'esoteric bullshit'
[taxonomies]
  series = 'series'