baseURL = 'https://esotericbullshit.net'
languageCode = 'en-us'
title = 'esoteric bullshit'
theme = "psychicwound"

enableInlineShortcodes = 'true'
summaryLength = '25'
paginate = 10

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = ['templates/*']

[menu]
    [[menu.nav]]
    identifier = "about"
    name = "about"
    pre = ""
    url = "/about"
    weight = 1   

[permalinks]
  [permalinks.page]
    week-notes = '/week-notes/:filename/'
  [permalinks.section]
    week-notes = '/week-notes/'

[params]
  description = 'arcane shit that I am incomprehensibly fixated on'
  title = 'esoteric bullshit'

[taxonomies]
  series = 'series'
  tags = 'tags'